### ISSUE TITLE
Include HTML form elements behind the scenes in composed dropdowns

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/clockface#127]
We could add a `<Select />` element inside `SelectDropdown` that is obscured from view but gets updated when the dropdown's selected value changes. This way when `SelectDropdown` is used in a form it behaves exactly as a `<Select />` element would. We would also have to expose ref for the obscured `<Select />`

**Comment by ShmuelLotman** [comment]
Closing. This was addressed and the issue is now stale
