### ISSUE TITLE
Standardize Popover component

### ISSUE THREAD

**Issue by mavarius** [influxdata/clockface#168]
Add a popover component that standardizes the interaction.

- [ ] Tip Text Popover
- [ ] Dismissable Popover

![image](https://user-images.githubusercontent.com/11937365/61314870-6ca0b700-a7b2-11e9-9fbb-e6c931ec75db.png)

![image](https://user-images.githubusercontent.com/11937365/61314871-6d394d80-a7b2-11e9-8bf3-5be9105f24b3.png)

![image](https://user-images.githubusercontent.com/11937365/61314888-79bda600-a7b2-11e9-8961-d66f1abe4d92.png)

![image](https://user-images.githubusercontent.com/11937365/61314928-8e01a300-a7b2-11e9-8fec-cf33838e753b.png)

![image](https://user-images.githubusercontent.com/11937365/61314805-4aa73480-a7b2-11e9-8d12-f8406b84b939.png)

**Comment by alexpaxton** [comment]
I think we are using [this library](https://github.com/wwayne/react-tooltip) in influxdb for tooltips, though not all tooltips use the component. Question is whether to build a styled version of the component in here, or roll our own solution using something like `ClickOutside` and some positioning logic

**Comment by mavarius** [comment]
The `ToolTip` and `PopOver` can still be two separate components with a consistent style across both.

**Comment by alexpaxton** [comment]
Created this issue https://github.com/influxdata/influxdb/issues/14536 to track the work required in InfluxDB.
