### ISSUE TITLE
Checkbox label does not wrap

### ISSUE THREAD

**Issue by ischolten** [influxdata/clockface#182]
**Describe the bug**
When there is a long label and the screen size shrinks, the label for a checkbox does not wrap. 

**To Reproduce**
1. Create a checkbox with a long label.
2. Shrink size
3. see the text not wrap

**Expected behavior**

**Screenshots**
<img width="497" alt="Screen Shot 2019-07-22 at 12 42 03 PM" src="https://user-images.githubusercontent.com/5751863/61660250-4f6e5b80-ac7e-11e9-9cbe-ec4f61eddfc1.png">

**Browser**
 - OS: mac
 - Browser: chrome

**Comment by alexpaxton** [comment]
Good catch!
