### ISSUE TITLE
Allow overlays to optionally fill the width of the screen

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/clockface#201]
Proposal 1:

If width is not specified to OverlayContainer then it should take up the full width of the screen (a la VEO)

Proposal 2:
Create  an alternative to OverlayContainer that produces a non-scrolling full-screen overlay a la VEO

**Comment by daviddkkim** [comment]
Fullscreen overlay 
https://us-east-1-1.aws.cloud2.influxdata.com/orgs/5ad804dc819b2ab5/dashboards/0743eaaf27dfa000/cells/0743eaaf350fb000/edit
