### ISSUE TITLE
Hidden inputs should not add whitespace

### ISSUE THREAD

**Issue by mavarius** [influxdata/clockface#203]
**Describe the bug**
Currently when an input type is hidden, the whitespace still gets added.

**Expected behavior**
Inputs, when the type is hidden, should not add additional space to the page

**Screenshots**
Two hidden inputs between dropdown and panel.
![image](https://user-images.githubusercontent.com/11937365/62321350-46884180-b457-11e9-9120-0bf5429382ef.png)

**Comment by daviddkkim** [comment]
Not sure if this is the case still - experiment w it 

hidden type should not take up space

**Comment by kristinarobinson** [comment]
closing due to age.
