### ISSUE TITLE
Add Range Slider Input

### ISSUE THREAD

**Issue by mavarius** [influxdata/clockface#209]
Add a Slider Input component for number range in a form. Should produce an HTML input of type `range`.

An input of type `number` exists but a slider is more useful for visualizing numbers and comparisons.

![image](https://user-images.githubusercontent.com/11937365/62659543-81d7b400-b920-11e9-9a59-cbfbe8613da2.png)

Props should include:
 - value
 - min
 - max
 - step
 - handle size
 - handle color

**Comment by alexpaxton** [comment]
https://jqueryui.com/slider/#rangemin this is a pretty good standard for this kind of component.

Debatable whether we need support for multiple handles or not, but I like these options:

- Can set to be vertical or horizontal
- Can toggle between filling the "range" in the track or not
- Can toggle between showing/hiding the range labels below the track
- Ability to disable the component
