### ISSUE TITLE
Index List should render EmptyState if children are undefined, null, or an empty array

### ISSUE THREAD

**Issue by mavarius** [influxdata/clockface#214]
Index List should render EmptyState if children are undefined, null, or an empty array.

Fix is currently in ResourceList.

**Comment by alexpaxton** [comment]
Looks like this is working as expected. The empty state logic for both components is in `IndexListBody` and `ResourceListBody`

**Comment by daviddkkim** [comment]
if children.length = 0 , then return the empty state prop  (new prop)

**Comment by kristinarobinson** [comment]
fixed with clockface 3.0
