### ISSUE TITLE
Header position options in resource list

### ISSUE THREAD

**Issue by ischolten** [influxdata/clockface#223]
Currently in the resource list, the headers are always to the far right of the list. 
I am currently using a custom component in the resource list other than the resource card and it looks weird with the headers all right aligned. I would like the option to configure the location of my headers.

Currently the alternative is overriding styles. 

<img width="880" alt="Screen Shot 2019-08-12 at 3 22 23 PM" src="https://user-images.githubusercontent.com/5751863/63044987-425f1980-be84-11e9-876b-cb84a0162b16.png">

**Comment by alexpaxton** [comment]
The headers are positioned to the right so that when a filter is added, they are opposite each other above the list. I suppose you could use a component spacer to align these differently. If you want the headers to line up with columns I'd suggest using `IndexList` instead

**Comment by alexpaxton** [comment]
Would you expect the headers to align left if there is no filter rendered?
