### ISSUE TITLE
Distinguish loading states in buttons

### ISSUE THREAD

**Issue by chnn** [influxdata/clockface#248]
This is a `SquareButton` that's transitioning from `ComponentStatus.Default` to `Loading` then back to `Default`. It would be awesome if there was a loading spinner that indicated what state it was in, and if it was not clickable during the `Loading` state. 

![loading state](https://user-images.githubusercontent.com/638955/63879562-d18a2800-c980-11e9-88b1-c1d4571e5bd7.gif)

**Comment by chnn** [comment]
Ah ok. I tried switching out the `SquareButton` for a `Button` but didn't have any more luck.

**Comment by alexpaxton** [comment]
Cannot reproduce
