### ISSUE TITLE
Allow popovers to be dismissed by a click anywhere

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/clockface#263]
In addition to `Click` I'd love to use `ClickAnywhere`.

When I am placing options inside the popover and I want to dismiss the popover when an option is clicked, I have to fumble with `onHide` to make it work. Ideally, there would be a way to dismiss the popover with a click anywhere on the screen.

**Comment by ShmuelLotman** [comment]
Closing. this exists currently, this issue is stale.
