### ISSUE TITLE
Remove Overlay family components in favor of Panel

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/clockface#332]
There is a lot of overlap between the `Panel` and `Overlay` families, so might be best to consolidate. The `Panel` family is more customizable so I vote we keep that as the set.

- [ ] Remove `OverlayBody` in favor of `PanelBody`
- [ ] Remove `OverlayHeader` in favor of `PanelHeader`
- [ ] Remove `OverlayFooter` in favor of `PanelFooter`
- [ ] Transfer `FlexBox` innards of `OverlayFooter` to `PanelFooter`

**Comment by daviddkkim** [comment]
If we replace the components, we would refactor the ui code to use panel instead of overlays

**Comment by mavarius** [comment]
The panels and overlays are no longer the same, so this change wouldn't work with the current design.
