### ISSUE TITLE
Port CodeSnippet from InfluxDB

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/clockface#343]
This seems pretty useful to have many places.

- [ ] Code can be copied
- [ ] Language can be specified
- [ ] Snippet can be configured to be "sensitive" (hidden by default, has a reveal button)

**Comment by daviddkkim** [comment]
https://github.com/influxdata/ui/blob/d7cf691473cd9ebdb1055dd636e39a391a2bcfec/src/shared/components/CodeSnippet.tsx

**Comment by mavarius** [comment]
Closing in favor of a Monaco implementation.
