### ISSUE TITLE
Port Dashboard family from InfluxDB

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/clockface#345]
Dependent upon https://github.com/influxdata/influxdb/issues/15495

First step is to refactor the dashboard and cell components to be purely presentational
Second step is to port them into clockface

**Comment by daviddkkim** [comment]
https://github.com/influxdata/ui/blob/d7cf691473cd9ebdb1055dd636e39a391a2bcfec/src/shared/components/cells/Cells.tsx


https://github.com/influxdata/ui/blob/d7cf691473cd9ebdb1055dd636e39a391a2bcfec/src/shared/components/cells/CellHeader.tsx

Entire dashboard and cell  as well as resizer and dragger.

**Comment by daviddkkim** [comment]
<div> that contains the content of the dashboard page.  like a cell grid

**Comment by brandenTenbrink** [comment]
Closing: Duplicate of #602
