### ISSUE TITLE
Refactor Inputs

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/clockface#346]
Currently there is one "base" input component that behaves more or less like a proxy of an HTML Input. However an HTML input is hyper flexible and from a styling and usability standpoint could be construed as a variety of components. It also has the issue of having many properties, many of which are only relevant to certain "types" of inputs.

I believe we could simplify this situation and provide a smoother dev experience by abstracting the input component into several specialized components

### Proposal:

- Create individual components for each "type" of input with more scoped props
  - Text
  - CheckBox
  - Number
  - RangeSlider (already done)
  - Radio
  - Time
  - URL
  - Password
  - Email
  - and more...

**Comment by alexpaxton** [comment]
After tinkering with `FormValidationElement` a bit I'm starting to think that the validation functionality it is providing belongs in `Input` instead

**Comment by daviddkkim** [comment]
Create a new epic with the components that are not done yet. Many of these are done.

**Comment by mavarius** [comment]
This implementation is not worth the maintenance cost it would incur.
