### ISSUE TITLE
Turn on CircleCI for clockface

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/clockface#354]
**Describe the bug**
CI has recently stopped working properly in clockface. This turns clockface into sadface.

**Expected behavior**
CI runs test and lint and fails branches that fail these checks.

**Comment by desa** [comment]
@hoorayimhelping any thing else that needs to be done for this issue?

**Comment by hoorayimhelping** [comment]
@desa I think we are good! thanks!
