### ISSUE TITLE
Mobile: Usage/Billing are responsive (mobile layout, mobile menu), but other pages are not

### ISSUE THREAD

**Issue by corriganjohn** [influxdata/clockface#370]
Discussed with Alex, screenshots from phone available.

On mobile phone (Android), when logging into Cloud 2, the Billing and Usage screens are displayed correctly in mobile format, but all other screens are being displayed full scale (reduced size to fit the display)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Browser**
 - OS: [e.g. Windows]

**Comment by alexpaxton** [comment]
Not sure if this issue is still relevant, but I think this belongs in the quartz repo not here since those pages are defined in that code base.
