### ISSUE TITLE
Scrollbars stories crash

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/clockface#378]
**Describe the bug**
Clicking either Scrollbar (at the bottom, under utilities) story causes a stack trace to be rendered

```js
str.replace is not a function
```
![Screen Shot 2019-11-08 at 2 02 00 PM](https://user-images.githubusercontent.com/146112/68513730-9a61ae00-0230-11ea-9eab-442b35536e0a.png)

**To Reproduce**
1. Go to https://influxdata.github.io/clockface/?path=/story/utilities-scrollbars--fixed-example

**Comment by alexpaxton** [comment]
The crash is no longer happening
