### ISSUE TITLE
[1.x] Unable to use keyboard to drive the Dropdown widget

### ISSUE THREAD

**Issue by randycoulman** [influxdata/clockface#439]
**Describe the bug**
When navigating a clockface-based UI (clockface 1.x) with the keyboard, I find that I am unable to interact properly with the Dropdown family of components without using my mouse.

**To Reproduce**
1. Go to https://influxdata.github.io/clockface/?path=/story/components-dropdowns-composed--selectdropdown
2. Click on the example dropdown to focus it, then click again to close it
3. Attempt to open the dropdown with the down arrow key. The dropdown doesn't open; instead, the entire page scrolls.
4. Open the dropdown with the space bar. It opens, as expected.
5. Attempt to highlight a different item with the arrow keys.  The entire page scrolls and the selection in the dropdown changes somewhat randomly.
6. Attempt to select the highlighted item with the Enter key.  The dropdown closes, but the original selection remains.

**Expected behavior**
1. At least the down arrow key and the space bar should open the dropdown.
2. Arrow up/down in the open dropdown should move the highlight to the next/previous item without scrolling the page.
3. Enter key should select the highlighted item

**Screenshots**

**Browser**
 - OS: OS/X Mojave
 - Browser Chrome
 - Version 80

**Comment by daviddkkim** [comment]
As soon as the menu opens, focus should be on first item. Allow arrow key to navigate once opened.

Semantic dropdown is + 100.

**Comment by kristinarobinson** [comment]
fixed with clockface 3.0
