### ISSUE TITLE
Add Disable Property to Input

### ISSUE THREAD

**Issue by Asalem1** [influxdata/clockface#440]
**Is your feature request related to a problem? Please describe.**
In specific situations, we should be able to disable the nput field. While not passing in an onChange function can resolve this functionality, we might want to have a more long-term solution for this. From a UX perspective, it's a little confusing to see an input field, only to click it and find out there's no way of editing it

The specific situation I'm thinking about is how the default variables are being rendered in the Variable Toolbar. Since they are default values, they should not be editable

**Comment by alexpaxton** [comment]
@Asalem1 you should be able to pass in a `ComponentStatus.Disabled` to `status`

**Comment by Asalem1** [comment]
Woops!
