### ISSUE TITLE
Tech Debt: Clean up build systems

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/clockface#471]
## Background

Currently clockface requires webpack configurations for storybooks and rollup configurations for building prod bundles.

Reducing the tech debt between these two systems would be nice.

**Comment by alexpaxton** [comment]
@hoorayimhelping currently Clockface build fails because of this line:
https://github.com/influxdata/clockface/blob/master/src/Styles/variables.scss#L518

It is blocking any new releases unfortunately. When typescript and some other dependencies were upgraded this became a problem

**Comment by ShmuelLotman** [comment]
Closing. There is a more recent issue that describes this and we dont need a duplicate
