### ISSUE TITLE
Improve keyboard interaction in overlays

### ISSUE THREAD

**Issue by mavarius** [influxdata/clockface#504]
**Is your feature request related to a problem? Please describe.**
Currently, when an overlay is open there is no keyboard interaction to close it. `TAB` navigation does not go to the close button, and the `ESC` key does not close the overlay. When an overlay is open the user should be able to exit it with keyboard interaction. This is an accessibility issue.

**Describe the solution you'd like**
AS a user with an overlay open
WHEN I press the `ESC` key
THEN the overlay should close

AS a user with an overlay open
WHEN I repeatedly press the `TAB` key
THEN it should only cycle through the options in the overlay
AND the close button should be selected as part of this rotation

**Describe alternatives you've considered**
Using arrow keys but they are not the correct interaction for this situation.

**Additional context**
![overlay_keyboard_nav](https://user-images.githubusercontent.com/11937365/81725012-19cb7680-943a-11ea-890a-155eae85717b.gif)

**Comment by ShmuelLotman** [comment]
Closing. the escape key can now close overlays.
