### ISSUE TITLE
Pendulum colors to the graph visualizations in Giraffe

### ISSUE THREAD

**Issue by mnorriswalker** [influxdata/clockface#513]
Some colors live in Giraffe and some in Clockface. Do we need to apply the newest color palette to Giraffe's visualization? There have been issues with contrast of colors on the line chart not be distinct enough to differentiation.

Per Will Cooke, "I look at the smoosh of colours between the top and the bottom of the list and see a jumble which my brain refuses to invest time in unpicking."
![image](https://user-images.githubusercontent.com/56005508/84809287-b398bd00-afbe-11ea-8bf5-daf25b711eb9.png)

**Comment by will** [comment]
nah, this is the first time i'm seeing those colors and i think they look
great

**Comment by daviddkkim** [comment]
Move to Giraffe
