### ISSUE TITLE
The Password Visibility Icons take keyboard focus

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/clockface#514]
**Describe the bug**
When tabbing through the signup form using my keyboard only, the eye icon takes tab focus, which is confusing and a bit jarring.

**To Reproduce**
1. Go to the quartz signup form in any environment
1. Use the keybaord to tab through the signup form
1. After entering your first password, hit `tab` on your keyboard to highlight the eye icon that stands for 'show password'

**Expected behavior**
Hitting tab on the first password field puts focus on the second password field, not the visibility toggle.

**Screenshots**

![in](https://user-images.githubusercontent.com/146112/85321533-a88bd400-b479-11ea-9885-4bded95c6c66.gif)

**Browser**
 - OS: MacOS
 - Browser Firefox

**Comment by alexpaxton** [comment]
While I agree it is a bit jarring the eye icon is technically a button and in the interest of accessibility it needs to be tab focusable

**Comment by alexpaxton** [comment]
@mavarius thoughts?

**Comment by daviddkkim** [comment]
Closing in-favor of https://github.com/influxdata/quartz/issues/4736
