### ISSUE TITLE
Allow the DatePicker to accept other time formats

### ISSUE THREAD

**Issue by mavarius** [influxdata/clockface#515]
**Is your feature request related to a problem? Please describe.**
Currently, to enter a custom time in the date picker it must match the format `YYYY-MM-DD [HH:mm:ss.SSS]`. This makes it difficult to quickly jump to a date or time.

**Describe the solution you'd like**
AS a user who needs to use a custom date/time
WHEN I enter the time in another format `eg. 01/15/2020 2pm`
THEN the date picker selects the appropriate date/time

**Describe alternatives you've considered**
- Add a dropdown or separate input for each field

**Additional context**
Existing DatePicker component
![image](https://user-images.githubusercontent.com/11937365/86947882-4382e000-c101-11ea-97a7-c220b361568c.png)

The underlying library React Datepicker allows multiple formats
![image](https://user-images.githubusercontent.com/11937365/86950028-6d89d180-c104-11ea-9ad2-ae87e9072dc9.png)

**Comment by daviddkkim** [comment]
Closing in favor of #608
