### ISSUE TITLE
ResourceCard.EditableName out of bounds input field when editing a name

### ISSUE THREAD

**Issue by Asalem1** [influxdata/clockface#517]
**Describe the bug**
The ResourceCard.EditableName input field is not confined to the ResourceCard width when editing a resource name:

![resource-card-edit-name](https://user-images.githubusercontent.com/19984220/87156206-2b31d300-c271-11ea-9063-4ff5668d286a.gif)

**Comment by ShmuelLotman** [comment]
closing. this is now addressed by: https://github.com/influxdata/ui/pull/627
