### ISSUE TITLE
Uncontrolled inputs

### ISSUE THREAD

**Issue by ischolten** [influxdata/clockface#552]
**Is your feature request related to a problem? Please describe.**
I would like an uncontrolled input plz so that we dont have to pass in our own onChange and value props. Regular html inputs support this.

**Describe the solution you'd like**
I would like an uncontrolled input plz.

**Describe alternatives you've considered**
Continue using controlled components.

**Additional context**
Am willing to contribute such things :))

**Comment by alexpaxton** [comment]
@ischolten open a pr!

**Comment by ShmuelLotman** [comment]
@ischolten is this something that is still needed?

**Comment by mavarius** [comment]
No longer needed.
