### ISSUE TITLE
Add drag to expand icon to icon font

### ISSUE THREAD

**Issue by mnorriswalker** [influxdata/clockface#578]
white -
https://drive.google.com/file/d/1Pdx4Cu2_QX79QmhccVjr92BIhWgYfxY1/view?usp=sharing

black -
https://drive.google.com/file/d/1Pdx4Cu2_QX79QmhccVjr92BIhWgYfxY1/view?usp=sharing

**Comment by mnorriswalker** [comment]
@ShmuelLotman any update? Thanks!

**Comment by mnorriswalker** [comment]
@ShmuelLotman - is this complete? please confirm. Trying to close this out. can you add the name of the icon?

**Comment by ShmuelLotman** [comment]
Added: Shield, ShieldSolid, Lock, DragToExpand
