### ISSUE TITLE
<Resource> should have ComponentStatus

### ISSUE THREAD

**Issue by TCL735** [influxdata/clockface#587]
**Is your feature request related to a problem? Please describe.**
`<Resource>` does not have any indication of an invalid or error state. In influxdb/ui we have a Variables resource which can have invalid names. These Variables may have been created outside of our UI or in a way that was not intended with an invalid name. 

**Describe the solution you'd like**
It would be great to be able to trigger the ComponentStatus to allow `<Resource>` to visually indicate that something is wrong with this resource.  See the screenshot below. Either the box, the name, or perhaps both should have some sort of color (or other visual cue) indicating it is invalid.

<img width="1680" alt="Screen Shot 2021-03-12 at 4 34 03 PM" src="https://user-images.githubusercontent.com/10736577/111012635-8b719b00-8351-11eb-979c-0409752b8ed1.png">

**Describe alternatives you've considered**
Right now, the only workaround is to pass in your own custom styles to the `<Resource>`

**Comment by daviddkkim** [comment]
Hey @TCL735 , 
I have a potentially dumb question - > is <Resource> a different component from <ResourceCard> ?
