### ISSUE TITLE
LargeDraggableResizer component looks like a scroll bar

### ISSUE THREAD

**Issue by mnorriswalker** [influxdata/clockface#615]
Just an idea... Can we update the [LargeDraggableResizer ](https://influxdata.github.io/clockface/?path=/story/layout-draggable-resizer-examples--2-panels)component to look less like a scroll bar? It's used:

- Notebooks
- Data Explorer

**Comment by daviddkkim** [comment]
Throwing some ideas here @juliajames12 

This is how google chrome does it 

![Screen Shot 2021-04-28 at 1 52 34 PM](https://user-images.githubusercontent.com/12561526/116471135-2d2d4880-a829-11eb-831f-fcc00c4d7b26.png)

**Comment by juliajames12** [comment]
Thanks @daviddkkim. Yeah, I like that execution. Let's users know they can resize the panel without hovering over the edge, but it doesn't feel like too much visual emphasis. I'm good with moving forward with this approach!

**Comment by daviddkkim** [comment]
![scrollbar](https://user-images.githubusercontent.com/12561526/116949252-871d7c00-ac36-11eb-8a78-07e01bc0b2b2.gif)

While awaiting further input from you, I decided to play around for a bit lol 

Some findings that might help you figure out the design :
- If the handle bar expanding and taking up a lot of space (physically and visually) bothers you, we have a few options or combinations of options to combat that :  
     1. make the expansion smaller 
     2. use a different gradient color/ or single color that pops less 
- We can play around with the shape of the pill pretty easily (I think) !

**Comment by juliajames12** [comment]
@daviddkkim This looks really great! It's a lot more subtle, even with the gradient. I think the size of the expansion is good and I believe that blue/purple gradient will work well among the other colors. 

The only thing we need to solve for still is having that pill work on lighter backgrounds. Here are some screenshots of how I pictured the resizer within notebooks and it would be on a lighter gray background than what's in this version. Would it be possible to have 2 variations? One for when it's implemented on a darker gray (lighter pills) and one for when it's implemented on a lighter gray (darker pills)?  

<img width="1366" alt="Screen Shot 2021-05-04 at 11 27 47 AM" src="https://user-images.githubusercontent.com/81173353/117028734-fbeec580-accb-11eb-8462-33e6379e49a2.png">
<img width="1232" alt="Screen Shot 2021-05-04 at 11 27 13 AM" src="https://user-images.githubusercontent.com/81173353/117028735-fc875c00-accb-11eb-9c1f-4a0a5ed63591.png">

**Comment by daviddkkim** [comment]
@juliajames12 yeah two variants should be no problem!

**Comment by daviddkkim** [comment]
So I took a look at your designs for notebooks where you want to use the resizer. I'm a tiny bit worried that the behavior of the resizer here won't meet exactly what you are looking for. Let's sync really quickly tomorrow on that !
