### ISSUE TITLE
Feature Request: Update LinkButton to take a `to` prop rather than `href`

### ISSUE THREAD

**Issue by Asalem1** [influxdata/clockface#623]
Currently the `LinkButton` that exists in clockface uses the `href` prop to direct a user to a given location. This is good if the user needs to be directed to an external domain, however if the user is being directed internally (i.e. a relative path), I would expect that we would want to use a `react-router-dom` `Link` component rather than an `a` tag with an `href` (the difference being that the transition to a page is smoother and requires less from the browser since we don't have to load the entire app but just a page).

Here's the component in question:

https://github.com/influxdata/clockface/blob/master/src/Components/Button/Composed/LinkButton.tsx

This feature request is relevant for the UI Unification work that's currently happening between Quartz and IDPE, since the UI will no longer be needing to redirect the user to an external part of the app (i.e. we won't need to direct the user to Quartz's UI to upgrade, they will be able to do that within the app)

**Comment by daviddkkim** [comment]
@Asalem1 Would replacing the link buttons with regular buttons and adding the route change to the onClick prop of the button component achieve this? Rather than using the link component. 

Could I close this issue?

**Comment by Asalem1** [comment]
Hey, sorry just seeing this. @daviddkkim. Not sure I understand what you're asking

**Comment by daviddkkim** [comment]
Hashed it out. Recommended using regula button with passing something like "history.push()" to the onProp for navigating

**Comment by Asalem1** [comment]
Wait, gonna reopen this since there was a bit of a misunderstanding here.

**Comment by Asalem1** [comment]
Yup, I completely misunderstood David. Gonna close it
