### ISSUE TITLE
Panel Menu and Submenu

### ISSUE THREAD

**Issue by mnorriswalker** [influxdata/clockface#624]
**Is your feature request related to a problem? Please describe.**
As a notebooks user, I can see actions, settings, and export options in a side menu so that I don't have overloaded panels with tons of options.

**Describe the solution you'd like**
We're currently building a custom two-tier side menu for panels in notebooks but we'd like to try to make this a reusable component to incorporate in other parts of the app!

**Additional context**
Design by @juliajames12

**Comment by juliajames12** [comment]
Design: 
<img width="234" alt="Screen Shot 2021-05-20 at 3 16 25 PM" src="https://user-images.githubusercontent.com/81173353/119036115-610a1280-b97e-11eb-88f2-45e0569e5f64.png">

Due by: 5/28

**Comment by mnorriswalker** [comment]
Maybe add the prototype link @juliajames12 ?

**Comment by juliajames12** [comment]
@daviddkkim We're going to build this custom for Notebooks and then we'll review if we want to include as a component to be used across the app.

**Comment by mavarius** [comment]
This is no longer needed.
