### ISSUE TITLE
'Account' Navigation element

### ISSUE THREAD

**Issue by corriganjohn** [influxdata/clockface#627]
GIVEN I am a user who belongs to more than one Account
WHEN I want to switch which Account I am working in
THEN I have a navigation element that visually identifies the Account

Acceptance Criteria

- [ ] Account 'icon' element that can be used wherever needed
- [ ] Uses (part of) the NAME of the account to visually identify which account
    - Proposed: Use the first two letters of the account 'Name'
- [ ] Uses color (gradient) to visually distinguish between different accounts
- [ ] Can be given a SIZE for display in different contexts

## Design
https://www.figma.com/file/vjpHxTfM3IDAroqFiOr6mq/Navigation-Switch-Account-Mar-2021?node-id=0%3A1

Notes on the design: This was concept design for the Account Switching function, and displays how the Account element would be used both in the main navigation and within an overlay menu.

**Comment by mavarius** [comment]
This was addressed by the multi-account project
