### ISSUE TITLE
PaginationNav middle values disappear when resizing the window when used with SimpleTable.

### ISSUE THREAD

**Issue by mtian725** [influxdata/clockface#654]
In the process of resolving a bug for the SimpleTable, I found a behavior regarding the pagination bar that might be a clockface issue. Essentially what is happening is sometimes when the page resizes, the middle values in the pagination bar does not render. It fixes itself when you click on the first page or last page. Currently, this issue does not occur on production but rather it is appearing due to a fix (https://github.com/influxdata/ui/pull/2252).

**To Reproduce**
1. Go to explore and put in a query
2. Switch to raw data view
3. Click on the last page
4. Click on the page before `...`
5. Resize the page
6. See that the middle numbers disappeared

**Example**

https://user-images.githubusercontent.com/39343323/128264224-3b96a28f-cf16-4ffd-b249-2c398f649842.mov

**Comment by mtian725** [comment]
Seems to only break when resizing it to be bigger on the last 4 pages (not including the last last page). 

https://user-images.githubusercontent.com/39343323/128416637-0b2bb57e-a394-4eaf-b5a8-2dea7832cef5.mov

**Comment by kristinarobinson** [comment]
@ChitlangeSahas - can you verify that this issue has been fixed?

**Comment by ChitlangeSahas** [comment]
This is fixed, we can close it.

https://user-images.githubusercontent.com/18511823/149029165-226bff96-c0ad-48f6-99d5-660cf9e90e59.mov
