### ISSUE TITLE
Dropdown component with a search filter and create option

### ISSUE THREAD

**Issue by juliajames12** [influxdata/clockface#684]
As a user, I'd like to be able to search through a large list of items within a dropdown and potentially create a new item (if applicable). 

We currently have a search dropdown available in Data Explorer, but it isn't a component. 

![Dropdown with Search](https://user-images.githubusercontent.com/81173353/139139792-724eca2f-b08f-4ace-8661-9b260e875201.png)

While creating this as a component, we'd like for the capability to add a "Create" option within the dropdown as well, so "Create ___" and search can coexist within one dropdown.

<img width="239" alt="Dropdown with Search and Create" src="https://user-images.githubusercontent.com/81173353/139139632-0d584f3c-5f68-438b-aaeb-13f90570e731.png">

**Comment by brandenTenbrink** [comment]
Closed: https://github.com/influxdata/clockface/pull/783
