### ISSUE TITLE
Dashboards: Hovering over a long graph name causes it to move

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/clockface#702]
>I think the edit icon thing needs to be absolute positioned to avoid this

https://user-images.githubusercontent.com/146112/140988129-c5c8c761-b6f7-4bae-a33d-f2601cd42139.mov

**Comment by TCL735** [comment]
It is not a long name per se, but rather a name that is long enough to barely fit the top line without the edit icon (pencil) while also too long to fit with the edit icon. When this happens, the line shifts from fitting to not fitting to give room for the edit icon.

**Comment by ChitlangeSahas** [comment]
This is fixed.
