### ISSUE TITLE
Bug: No way to open a dashboard in a new tab on Linux

### ISSUE THREAD

**Issue by 8none1** [influxdata/clockface#723]
## About the bug

**Steps to reproduce:**
1. Open the Dashboard list page
2. ctrl-click on a Dashboard
3. Notice that the page is not opened in a new tab

**Expected behavior:**

Using the ctrl-click mechanism should open in a new tab.  

**Actual behavior:**

Page opens in the same tab.
While "super" click does open the page in a new tab, this is not correct behaviour anywhere other than a Mac.
ctrl-click is the browser default action for "open link in a new tab".

## About your environment

**Environment info:**

- Linux 5.10.0-1050-oem x86_64
- Cloud 2
- Chrome

A similar issue was addressed in https://github.com/influxdata/ui/pull/2687
However, that uses meta-click, which is only correct for a Mac.
ctrl-clicking on items in the left nav bar *does* open in a new tab.

**Comment by kristinarobinson** [comment]
>Actually, there is a complete inconsistency here. ctrl-click on items in the vertical bar on the left results in opening in a new tab. Super-click results in a new tab on the, for example, dashboard grid view.

the most straightforward solution here is to make ResourceCard.EditableName an <a> not a <div>

**Comment by 8none1** [comment]
Is this deployed in to either Tools or Prod now?  Looking at Glance I think it is.

Also use the inspector I see that the element is now an `<a>`.

However, this has not fixed the problem.
