### ISSUE TITLE
Branding: Update Clockface version to reflect new logo

### ISSUE THREAD

**Issue by Luckette** [influxdata/clockface#745]
The new logo and brand identity was rolled out during the weekend of February 19-20. The new logo is likely to land in Clockface version 3.4.0. ? 

 Also, update the favicon icon.

@mavarius is leading the Clockface updates.

**Comment by kristinarobinson** [comment]
Attached new logo file to be used in clockface.
![InfluxDB_cubo](https://user-images.githubusercontent.com/70343856/159070157-481af6ad-ee6e-47f7-b3b1-4b0aa5455c16.svg)

**Comment by TCL735** [comment]
Getting the new logo into both parts, "simplified" and non-simplified is extremely difficult unless the developer knows how to draw the paths manually. Attempting to apply the color gradient by replacing only one section of the code does not seem to work well.

Here is a video of the attempt:


https://user-images.githubusercontent.com/10736577/159586531-9668c5ff-7d38-4c5a-806a-93d754369fb1.mp4

**Comment by TCL735** [comment]
@kristinarobinson @Luckette this work may be better suited for our design team.
