### ISSUE TITLE
Create InfluxDB Cloud icon + wordmark component

### ISSUE THREAD

**Issue by juliajames12** [influxdata/clockface#748]
Right now, we don't have a component that has both the icon and InfluxDB cloud wordmark combined. This can cause issues with relative sizing and spacing when implemented which causes inconsistent branding. We should have a component with those two elements combined. 

Correct implementation (top) vs. incorrect implementation (bottom):
<img width="890" alt="Screen Shot 2022-03-24 at 11 58 06 AM (1)" src="https://user-images.githubusercontent.com/81173353/160158934-b632cfc4-5e41-479e-a64b-015f78a134c5.png">

**Comment by brandenTenbrink** [comment]
This issue will be solved in conjunction with the need to move all possible Logo branding into Clockface.

**Comment by brandenTenbrink** [comment]
The new logo did address this, but it needs some additional work to make happen. Will be pairing with Bill

**Comment by taramk** [comment]
Just to add in case it helps, Kristina said they need: Kubo alone, Kubo+wordmark, and wordmark alone

**Comment by brandenTenbrink** [comment]
closed by: https://github.com/influxdata/clockface/pull/757
