### ISSUE TITLE
Add new icons to Clockface

### ISSUE THREAD

**Issue by juliajames12** [influxdata/clockface#749]
Add the following remix icons in clockface:

- terminal-line
![terminal-line (1)](https://user-images.githubusercontent.com/81173353/160684871-cf0b99be-d84a-4581-81c7-fce87f0f38b5.svg)
- organization-chart
![organization-chart (1)](https://user-images.githubusercontent.com/81173353/160684954-defe544b-e033-4722-bc8a-9f9c464e1d52.svg)
- table-line
![table-line (1)](https://user-images.githubusercontent.com/81173353/160685037-156d5732-6f11-4fc2-a2dc-6c52b4eedc55.svg)
- calendar-2-line
![calendar-2-line (1)](https://user-images.githubusercontent.com/81173353/160686219-fc6f52ff-e782-4bcc-a921-42341696dba1.svg)

**Comment by brandenTenbrink** [comment]
Icons have been published through the above PR
