### ISSUE TITLE
Add collapse and open to draggable resizer

### ISSUE THREAD

**Issue by juliajames12** [influxdata/clockface#782]
We'd like to add the following design and function to the draggable resizer so users are able to easily collapse and open the side panels in the new query experience. 

- There should be a prop in the component to allow developers to turn collapse and open on or off
- There should be a prop in the component that allows developers to have the panel open or closed by default
- There should be a prop to indicate if the resizer is being used for a left or right panel - this will change the icon and direction the panel will close and open from
- When the panel menu is closed, the draggable resizer isn't shown
- Use the new collapse/open icon to indicate which direction the panel will open and close

Draggable resizer (right panel) open
<img width="496" alt="Screen Shot 2022-06-15 at 12 50 28 PM" src="https://user-images.githubusercontent.com/81173353/173882558-56fca799-af2c-440e-8771-9b52b2e9458d.png">

Draggable resizer (right panel) closed
<img width="496" alt="Screen Shot 2022-06-15 at 12 51 17 PM" src="https://user-images.githubusercontent.com/81173353/173882791-1509d220-00fd-4a99-8d5a-14ec6dab4b96.png">

Link to Figma: https://www.figma.com/file/0qAntPk5LVangAHguWT74X/Query-Experience-Project?node-id=1258%3A53744

Outstanding question: Do I need to update the open/close icon to match any changes that we're making to the icon set?

**Comment by brandenTenbrink** [comment]
https://github.com/influxdata/clockface/pull/814
