### ISSUE TITLE
Update font color on ResourceCardDescription

### ISSUE THREAD

**Issue by taramk** [influxdata/clockface#785]
The current color does not pass contrast standards. We should match what we are using in Figma, which is our "g75" grey—#B9B9C5. This color change should apply to the default state of ResourceCardEditableDescription as well.

Figma:
https://www.figma.com/file/W8Xpu3GjL2xSU9tbZCY9B0/Clockface-4.0?node-id=330%3A2052

Clockface:
https://influxdata.github.io/clockface/?path=/story/components-cards-resourcecard-family--resourcecarddescription

**Comment by mavarius** [comment]
Closing as #817 will address this issue.
